include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  CORE_STABLE: 10.4
  _SHOW_ENVIRONMENT_VARIABLES: 1

phpcs:
  allow_failure: false

phpstan:
  allow_failure: false

stylelint:
  allow_failure: false

eslint:
  allow_failure: false

phpunit:
  allow_failure: false
